#!/usr/bin/env bash
# ==============================================================================
# SENTROID — create the ONE permanent fleet signing key.
#
# Why this exists: the Device Owner provisioning QR embeds
# PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM, and Android refuses to provision
# if the downloaded APK's signing certificate doesn't match it. The debug
# keystore is generated per-machine, so debug-signed builds produce a different
# checksum on every computer — every QR printed before would stop working.
#
# This key is the organization's permanent MDM identity. Generate it ONCE, back
# it up, and never lose it: without it you cannot ship an update that upgrades
# an already-deployed agent (Android rejects an APK signed by a different key),
# and every enrolled device would need a factory reset + re-provision.
#
# Run:  ./make-release-key.sh
# Then: ./build-apk.sh --release      (see build-apk.sh)
# ==============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEYSTORE="$ROOT/sentroid-release.jks"
PROPS="$ROOT/keystore.properties"
ALIAS="sentroid"

if [ -f "$KEYSTORE" ]; then
  echo "Keystore already exists: $KEYSTORE"
  echo "Refusing to overwrite it — replacing the fleet key would break updates"
  echo "for every already-enrolled device. Delete it deliberately if you truly"
  echo "mean to start a new fleet identity."
  exit 1
fi

# keytool lives in the JDK; reuse the same 17-21 JDK the app build requires.
java_major() { "$1/bin/java" -version 2>&1 | sed -n 's/.*version "\([0-9]*\).*/\1/p' | head -1; }
JDK="${JAVA_HOME:-}"
if [ -z "$JDK" ] || [ ! -x "$JDK/bin/keytool" ] || ! echo "$(java_major "$JDK")" | grep -qE '^(17|18|19|20|21)$'; then
  JDK=""
  for c in /opt/android-studio/jbr "$HOME/android-studio/jbr" \
           /usr/lib/jvm/java-21-openjdk /usr/lib/jvm/java-17-openjdk; do
    if [ -x "$c/bin/keytool" ] && echo "$(java_major "$c")" | grep -qE '^(17|18|19|20|21)$'; then
      JDK="$c"; break
    fi
  done
fi
[ -n "$JDK" ] || { echo "No JDK 17-21 with keytool found. Set JAVA_HOME." >&2; exit 1; }

# Random passwords: nothing is typed twice, and the credentials only ever live
# in keystore.properties (gitignored, chmod 600) beside the keystore itself.
STORE_PASS="$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 24)"

echo "[make-release-key] generating 10000-day RSA-4096 fleet key…"
"$JDK/bin/keytool" -genkeypair \
  -keystore "$KEYSTORE" \
  -alias "$ALIAS" \
  -keyalg RSA -keysize 4096 \
  -validity 10000 \
  -storepass "$STORE_PASS" \
  -keypass "$STORE_PASS" \
  -dname "CN=SENTROID MDM Agent, OU=IT, O=SENTROID, L=, S=, C=" \
  >/dev/null 2>&1

cat > "$PROPS" <<EOF
# SENTROID fleet signing credentials — NEVER COMMIT THIS FILE.
# Generated by make-release-key.sh. Back up alongside sentroid-release.jks:
# losing either one means no enrolled device can ever be updated again.
storeFile=$KEYSTORE
storePassword=$STORE_PASS
keyAlias=$ALIAS
keyPassword=$STORE_PASS
EOF
chmod 600 "$PROPS" "$KEYSTORE"

echo ""
echo "============================================================"
echo " Fleet signing key created."
echo "   Keystore : $KEYSTORE"
echo "   Config   : $PROPS   (gitignored, chmod 600)"
echo ""
echo " >>> BACK BOTH FILES UP NOW, somewhere off this machine. <<<"
echo " Without them you cannot update the agent on enrolled devices."
echo ""
echo " Next: ./build-apk.sh --release"
echo " The printed signature checksum is now permanent — the value the"
echo " provisioning QR will carry for the life of the fleet."
echo "============================================================"
